name: Build and Push Docker Image

on:
  push:
    branches:
      - master  # or any other branch you want to trigger the build on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Updated version 1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1  # Updated version
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t myusername/flask-todo:latest .

      - name: Push Docker image
        run: docker push myusername/flask-todo:latest
